extends Node

@onready var gems = %GEMS

@export var inventory_dictionary : Dictionary = {
	"GUI_INVENTORY_ROW1_1_PATH":"%GUI_INVENTORY_ROW1_1",
	"GUI_INVENTORY_ROW1_1_GEM":"empty",
	"GUI_INVENTORY_ROW1_2_PATH":"%GUI_INVENTORY_ROW1_2",
	"GUI_INVENTORY_ROW1_2_GEM":"empty",
	"GUI_INVENTORY_ROW1_3_PATH":"%GUI_INVENTORY_ROW1_3",
	"GUI_INVENTORY_ROW1_3_GEM":"empty",
	"GUI_INVENTORY_ROW1_4_PATH":"%GUI_INVENTORY_ROW1_4",
	"GUI_INVENTORY_ROW1_4_GEM":"empty",
	"GUI_INVENTORY_ROW1_5_PATH":"%GUI_INVENTORY_ROW1_5",
	"GUI_INVENTORY_ROW1_5_GEM":"empty",
	"GUI_INVENTORY_ROW1_6_PATH":"%GUI_INVENTORY_ROW1_6",
	"GUI_INVENTORY_ROW1_6_GEM":"empty",
	"GUI_INVENTORY_ROW1_7_PATH":"%GUI_INVENTORY_ROW1_7",
	"GUI_INVENTORY_ROW1_7_GEM":"empty",
	"GUI_INVENTORY_ROW1_8_PATH":"%GUI_INVENTORY_ROW1_8",
	"GUI_INVENTORY_ROW1_8_GEM":"empty",
	"GUI_INVENTORY_ROW1_9_PATH":"%GUI_INVENTORY_ROW1_9",
	"GUI_INVENTORY_ROW1_9_GEM":"empty",
	"GUI_INVENTORY_ROW1_10_PATH":"%GUI_INVENTORY_ROW1_10",
	"GUI_INVENTORY_ROW1_10_GEM":"empty",
	"GUI_INVENTORY_ROW2_1_PATH":"%GUI_INVENTORY_ROW2_1",
	"GUI_INVENTORY_ROW2_1_GEM":"empty",
	"GUI_INVENTORY_ROW2_2_PATH":"%GUI_INVENTORY_ROW2_2",
	"GUI_INVENTORY_ROW2_2_GEM":"empty",
	"GUI_INVENTORY_ROW2_3_PATH":"%GUI_INVENTORY_ROW2_3",
	"GUI_INVENTORY_ROW2_3_GEM":"empty",
	"GUI_INVENTORY_ROW2_4_PATH":"%GUI_INVENTORY_ROW2_4",
	"GUI_INVENTORY_ROW2_4_GEM":"empty",
	"GUI_INVENTORY_ROW2_5_PATH":"%GUI_INVENTORY_ROW2_5",
	"GUI_INVENTORY_ROW2_5_GEM":"empty",
	"GUI_INVENTORY_ROW2_6_PATH":"%GUI_INVENTORY_ROW2_6",
	"GUI_INVENTORY_ROW2_6_GEM":"empty",
	"GUI_INVENTORY_ROW2_7_PATH":"%GUI_INVENTORY_ROW2_7",
	"GUI_INVENTORY_ROW2_7_GEM":"empty",
	"GUI_INVENTORY_ROW2_8_PATH":"%GUI_INVENTORY_ROW2_8",
	"GUI_INVENTORY_ROW2_8_GEM":"empty",
	"GUI_INVENTORY_ROW2_9_PATH":"%GUI_INVENTORY_ROW2_9",
	"GUI_INVENTORY_ROW2_9_GEM":"empty",
	"GUI_INVENTORY_ROW2_10_PATH":"%GUI_INVENTORY_ROW2_10",
	"GUI_INVENTORY_ROW2_10_GEM":"empty"
	}


func _on_inventory_gui_input(event: InputEvent, extra_arg_0: String) -> void:
	if event is InputEventMouseButton and event.button_index == MOUSE_BUTTON_LEFT:
		if gems.selected_gem == null :
					pass
		else:
			if inventory_dictionary["GUI_INVENTORY_ROW" + extra_arg_0 + "_GEM"] == "empty":
				inventory_dictionary["GUI_INVENTORY_ROW" + extra_arg_0 + "_GEM"] = gems.selected_gem.name
				gems.gem_movement(get_node(inventory_dictionary["GUI_INVENTORY_ROW" + extra_arg_0  + "_PATH"]))
				gems.gem_was_unselected()
